site:
  title: Body of Knowledge for Apache Maven
  start_page: mavenbestpractices::overview.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_paths: [ ./ ]

ui:
  bundle:
    url: https://github.com/obfischer/antora-ui-obfischer/releases/download/2025-04-12/ui-bundle.zip
    snapshot: true

asciidoc:
  extensions:
    - asciidoctor-kroki
