site:
  title: Body of Knowledge for Apache Maven
  start_page: mavenbestpractices::overview.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_paths: [ ./ ]

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  extensions:
    - asciidoctor-kroki
